fixing pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -54,7 +54,7 @@ jobs:
           set -e
           . "$IDF_PATH/export.sh"
           cd build
-          esptool.py --chip esp32 merge-bin --pad-to-size 4MB -o flash_image.bin @flash_args || { echo "Error generando imagen de flash"; exit 1; }
+          esptool --chip esp32 merge-bin --pad-to-size 4MB -o flash_image.bin @flash_args || { echo "Error generando imagen de flash"; exit 1; }
           # Crear output.log vacío para evitar errores de grep
           : > output.log
           timeout ${IDF_TIMEOUT}s qemu-system-xtensa \
@@ -69,7 +69,11 @@ jobs:
           for i in $(seq 1 ${IDF_TIMEOUT}); do
             if grep -q "OK" output.log; then
               echo "Tests finalizados, matando QEMU..."
-              kill $QEMU_PID
+              if kill -0 $QEMU_PID 2>/dev/null; then
+                kill $QEMU_PID
+              else
+                echo "QEMU ya terminó antes de kill."
+              fi
               break
             fi
             sleep 1
